apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-proxy
  name: frontend-proxy
  namespace: mc
spec:
  ports:
  - port: 80
    targetPort: 4180
  selector:
    app: frontend-proxy
  type: ClusterIP